### ISSUE TITLE
Regenerate the sponsors site

### ISSUE THREAD

**Issue by gotmax23** [FrostyX/fedora-sponsors#19] opened 2023-05-08 18:25 UTC
https://docs.pagure.org/fedora-sponsors/ hasn't been updated since 2023-03-21 according to the footer. I added a sponsor.yaml for myself (https://gotmax23.fedorapeople.org/sponsor.yaml) on 2023-04-03, but I still don't show up on the site.

**Comment by FrostyX** [comment] 2023-05-08 23:05
Hello @gotmax23,
thank you for the report.

It must have gotten stuck ... again. I will poke it as soon as I can.

**Comment by gotmax23** [comment] 2023-05-08 23:37
Thanks @FrostyX!

**Comment by FrostyX** [comment] 2023-06-05 21:19
Oh, I didn't realize this is caused by #18.
Please subscribe and let me close this one.

**Closed as completed by FrostyX** 2023-06-05 21:19 UTC
